---
- hosts: all
  tags: [mac, linux]
  tasks:
  - name: install neovim pip package
    pip: name=neovim state=latest

  - name: install neovim pip3 package
    pip: name=neovim state=latest executable=/usr/local/bin/pip3
  #   pip: name=neovim state=latest extra_args=--user

  - name: clone vim config
    git:
      repo: https://github.com/masters-of-cats/a-new-hope
      dest: ~/.config/nvim
      force: yes

  - name: install vim plugins and binaries
    command: nvim --headless +PlugInstall +PlugUpdate +GoUpdateBinaries +qall

  - name: update remote plugins
    command: nvim --headless +UpdateRemotePlugins +qall

  - name: get bash-it
    git:
      repo: https://github.com/Bash-it/bash-it.git
      dest: ~/.bash_it

  - name: install bash-it
    command: ~/.bash_it/install.sh --silent

  - name: set bash-it prompt
    replace:
      path: ~/.bashrc
      regexp: 'bobby'
      replace: 'minimal'

  - name: get TPM
    git:
      repo: https://github.com/tmux-plugins/tpm
      dest: ~/.tmux/plugins/tpm

  - file: path=~/bin state=directory mode=0755

  - name: install counterfeiter
    command: go get -u github.com/maxbrunsfeld/counterfeiter

  - name: set up symlinks
    file:
      path: "{{item.target}}"
      src: "{{item.src}}"
      state: link
      force: yes
    with_items:
    - {target: ~/.bash_it/custom/completion.bash, src: "{{ansible_env.PWD}}/config/bash/completion.bash"}
    - {target: ~/.git-authors, src: "{{ansible_env.PWD}}/config/.git-authors"}
    - {target: ~/.bash_it/custom/ngrok.bash, src: "{{ansible_env.PWD}}/config/bash/ngrok.bash"}
    - {target: ~/.bash_it/custom/alias.bash, src: "{{ansible_env.PWD}}/config/bash/alias.bash"}
    - {target: ~/.tmux.conf, src: "{{ansible_env.PWD}}/config/tmux.conf"}
    - {target: ~/.bash_it/custom/env.bash, src: "{{ansible_env.PWD}}/config/bash/env.bash"}
    - {target: ~/.bash_it/custom/git.bash, src: "{{ansible_env.PWD}}/config/bash/git.bash"}
    - {target: ~/.bash_it/custom/profile.bash, src: "{{ansible_env.PWD}}/config/bash/profile.bash"}
    - {target: ~/.bash_it/custom/terminal.bash, src: "{{ansible_env.PWD}}/config/bash/terminal.bash"}
    - {target: ~/.gitconfig-dot, src: "{{ansible_env.PWD}}/config/.gitconfig-dot"}
    - {target: ~/.git-commit, src: "{{ansible_env.PWD}}/config/.git-commit"}
    - {target: ~/.hushlogin, src: "{{ansible_env.PWD}}/config/.hushlogin"}

  - name: ~/.gitconfig
    blockinfile:
      path: ~/.gitconfig
      create: yes
      block: |
        [include]
          path = ~/.gitconfig-shared

  - name: install git-co-authored-by-hook
    environment:
      GIT_DUET_CO_AUTHORED_BY: 1
    command: bash -c "git solo \"$( grep authors -A 1 ~/.git-authors | tail -1 | cut -d ':' -f 1 | tr -d '[:space:]' )\""
