---
- hosts: all
  tags: [linux]
  vars:
    downloads_dir: /tmp/downloads
    go_version: 1.21.5
    ngrok_version: v3
    ngrok_url: bNyj1mQVY4c
    kind_version: 0.20.0
    k9s_version: 0.30.7
    git_duet_version: 0.10.0
    vagrant_version: 2.4.0

  tasks:
  - name: ensure downloads directory exists
    file: path={{downloads_dir}} state=directory

  - name: add apt repositories
    become: yes
    become_method: sudo
    apt_repository: repo={{ item }}
    with_items:
    - ppa:git-core/ppa
    - ppa:neovim-ppa/unstable

  # - name: add Google Cloud repository
  #   become: yes
  #   become_method: sudo
  #   lineinfile: dest=/etc/apt/sources.list.d/google-cloud-sdk.list line='deb https://packages.cloud.google.com/apt cloud-sdk main' create=yes

  # - name: add Google Cloud repository key
  #   become: yes
  #   become_method: sudo
  #   apt_key: url=https://packages.cloud.google.com/apt/doc/apt-key.gpg

  - name: add VirtualBox repository
    become: yes
    become_method: sudo
    lineinfile: dest=/etc/apt/sources.list.d/virtualbox.list line="deb http://download.virtualbox.org/virtualbox/debian {{ansible_distribution_release}} contrib" create=yes

  - name: add VirtualBox repository key
    become: yes
    become_method: sudo
    apt_key: url=https://www.virtualbox.org/download/oracle_vbox_2016.asc

  # - name: add Vagrant repository
  #   become: yes
  #   become_method: sudo
  #   lineinfile: dest=/etc/apt/sources.list.d/hasicorp.list line="deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ansible_distribution_release}} main" create=yes

  # - name: add Vagrant repository key
  #   become: yes
  #   become_method: sudo
  #   apt_key: url=https://www.virtualbox.org/download/oracle_vbox_2016.asc
  # wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg

  - name: install Vagrant
    become: yes
    become_method: sudo
    apt:
      deb: https://releases.hashicorp.com/vagrant/{{vagrant_version}}/vagrant_{{vagrant_version}}_x86_64.deb

  - name: install apt packages
    become: yes
    become_method: sudo
    apt:
      state: latest
      update_cache: yes
      name:
      - terraform
      - vlan
      - isc-dhcp-server
      - firewalld
      - ack-grep
      - apt-transport-https
      - ca-certificates
      - gnupg
      - cmake
      - curl
      - direnv
      - exuberant-ctags
      - fonts-inconsolata
      - git
      - google-cloud-sdk
      - htop
      - lastpass-cli
      - mercurial
      - neovim
      # - python-dev
      # - python-pip
      # - python3-dev
      - python3-pip
      - shellcheck
      - silversearcher-ag
      - tree
      - vim
      - vim-nox
      - virtualbox-6.1
      # - vagrant
      - wget
      - xclip
        #- ngrok-client
      - ripgrep
      # For tmux
      - libevent-dev
      - libncurses5-dev
      - ncurses-dev
      - build-essential
      - bison
      - pkg-config

  - name: download ngrok
    get_url: url=https://bin.equinox.io/c/{{ngrok_url}}/ngrok-{{ngrok_version}}-stable-linux-amd64.tgz dest={{downloads_dir}}/ngrok.tgz

  - name: extract ngrok
    unarchive: copy=no src={{downloads_dir}}/ngrok.tar.gz dest={{ ansible_env.HOME }}/.local/bin creates={{ ansible_env.HOME }}/.local/bin/ngrok

  - name: download kind
    become: yes
    become_method: sudo
    get_url: url= https://kind.sigs.k8s.io/dl/v{{kind_version}}/kind-linux-amd64 dest=/usr/local/bin

  - name: chmod kind
    become: yes
    become_method: sudo
    command: chmod +x /usr/local/bin/kind

  - name: download k9s
    get_url: url=https://github.com/derailed/k9s/releases/download/v{{k9s_version}}/k9s_Linux_amd64.tar.gz dest={{downloads_dir}}/k9s.tar.gz

  - name: extract k9s
    unarchive: copy=no src={{downloads_dir}}/k9s.tar.gz dest={{ ansible_env.HOME }}/.local/bin creates={{ ansible_env.HOME }}/.local/bin/k9s

  # - name: install pip3
  #   pip: name=pip state=latest extra_args=--user executable=/usr/bin/pip3

  # - name: install neovim pip3 package
  #   pip: name=neovim state=latest extra_args=--user

  - name: download go
    get_url: url=https://golang.org/dl/go{{go_version}}.linux-amd64.tar.gz dest={{downloads_dir}}/go.tar.gz

  - name: extract go
    become: yes
    become_method: sudo
    unarchive: copy=no src={{downloads_dir}}/go.tar.gz dest=/usr/local creates=/usr/local/go

  - name: ensure git-apps directory exists
    file: path=~/git-apps state=directory

  - name: download git duet
    get_url: url=https://github.com/git-duet/git-duet/releases/download/{{git_duet_version}}/linux_amd64.tar.gz dest={{downloads_dir}}/git-duet.tar.gz

  - name: install git duet
    unarchive: copy=no src={{downloads_dir}}/git-duet.tar.gz dest={{ ansible_env.HOME }}/.local/bin creates={{ ansible_env.HOME }}/.local/bin/git-duet
