---
- hosts: all
  tags: [m-rcd]
  tasks:
  - name: get asdf
    git:
      repo: https://github.com/asdf-vm/asdf.git
      dest: ~/.asdf
      version: v0.7.5

  - name: set up personal symlinks
    file:
      path: "{{item.target}}"
      src: "{{item.src}}"
      state: link
      force: yes
    with_items:
    - {target: ~/.git-authors, src: "{{ansible_env.PWD}}/config/.git-authors-m"}
    - {target: ~/.bash_it/custom/custom.bash, src: "{{ansible_env.PWD}}/config/bash/custom_m.bash"}
